#server:
#  port: 8089
#
## SQL Server
#spring:
#  config:
#    import: optional:file:.env[.properties]
#  datasource:
#    url: jdbc:sqlserver://${E_BALITA_DB_IP:localhost}:${E_BALITA_DB_PORT:1433};databaseName=ebalitadb
#    username: ${DATABASE_USERNAME:sa}
#    password: ${DATABASE_PASSWORD:12345678}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect
#      show-sql: true


spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=ebalitadb
    username: sa
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true


# JWT
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expireMs: 600000 # 10 Minutes
  refrEshexpireMs: 120000




























#spring:
#  datasource:
#    url: jdbc:sqlserver://;serverName=localhost;databaseName=ebalitadb;encrypt=true;trustServerCertificate=true;
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    username: sa
#    password: 12345678
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect
#      show-sql: true














